[Implement] Buffer Read/Write 32 Bit Int/Float
AssemblyScript/node pull request #19
Opened 2019-07-28 00:08 UTC by RedDwarfian

2019-07-28 01:49 UTC, dcodeIO commented on assembly/buffer/index.ts
> +    return reinterpret<f32>(load<i32>(this.dataStart + <usize>offset));
Can just `load<f32>` here

2019-07-28 01:50 UTC, dcodeIO commented on assembly/buffer/index.ts
> +    store<i32>(this.dataStart + offset, reinterpret<i32>(value));
Can just `store<f32>` here

2019-08-01 22:57 UTC, jtenner approved these changes
This pull request looks excellent now.

@dcodeio?

2019-08-01 23:13 UTC, MaxGraey commented
It seems this PR miss `readDoubleLE/readDoubleBE` and `writeDoubleLE/writeDoubleBE`?

2019-08-02 00:40 UTC, jtenner commented
He told me he wanted to cover the 32 bit operations in this pull request. He already started work on those functions elsewhere.

2019-08-02 08:17 UTC, MaxGraey commented
Got it

2019-08-03 14:09 UTC, jtenner requested changes
One last nitpick.

```ts
if (i32(offset < 0)... 
```

Can we put a space between the if and each parenthesis in the `assembly/buffer/index.ts` file?

Once this is done, I'll pull the request.

2019-08-06 14:03 UTC, MaxGraey commented
LGTM

2019-08-06 14:05 UTC, merged